POST http://localhost:18080/setting
Content-Type: application/json

{
  "urls": ["http://localhost:1081", "http://localhost:1082", "http://localhost:1083"],
  "intervalMs": 10000
}

###
GET http://localhost:18080/setting
Accept: application/json

###
GET http://localhost:18080/health